site_name: Evraon
site_url: https://evraon.com/
extra_css: [assets/styles/extra.css]
extra_javascript: [assets/js/extra.js]
docs_dir: 'docs'
site_dir: 'generated'

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg
  custom_dir: 'overrides'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    #- navigation.tracking
    #- navigation.tabs.sticky
    #- navigation.sections

extra:
  alternate:
    - name: English
      link: /en/docs/
      lang: en

    - name: Русский
      link: /ru/docs/
      lang: ru
    
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/evraon

    - icon: fontawesome/brands/github
      link: https://github.com/avently
  
markdown_extensions:
    - toc:
        permalink: ⚓
    - pymdownx.tabbed
    - pymdownx.superfences
    #- admonition
nav:
  - Home: index.md
  - Docs:
    - Start:
      - docs/index.md
      - docs/installation.md
      - docs/structure.md
    - Tasks:
      - Main settings: docs/tasks/main.md
      - docs/tasks/demo.md
    
    - Strategies:
      - Main settings: docs/strategies/main.md
      - docs/strategies/scalper.md
      - docs/strategies/flash.md
      - docs/strategies/highlow.md
    - Exchanges:
      - docs/connectors/binance.md
      - docs/connectors/bitmex.md
      - docs/connectors/quik.md

plugins:
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        en: ENG
        ru: РУС
      nav_translations:
        ru:
          Home: Главная
          Start: Начало
          Main settings: Основные настройки
          Docs: Документация
          Exchanges: Биржи
          Strategies: Стратегии
          Tasks: Задачи
        en:
          Connectors: Exchanges

copyright: Copyright &copy; 2018 - 2021 Stanislav Dmitrenko - <a href="/en/terms/">Terms Of Use</a> - <a href="/en/privacy/">Privacy Policy</a>